"""SecureRAG Phase 5 ranking explanation helpers.

This module turns prioritized CVE rankings into short analyst-facing
explanations generated by the local Mistral model through Ollama.
"""

from __future__ import annotations

import logging
from datetime import datetime, timezone
from typing import Any, Dict, List, Mapping

from modules.priority_scorer import WEIGHTS_MAIN, rank_cves

LOGGER = logging.getLogger(__name__)
DEFAULT_MODEL = "mistral"


def _configure_logging() -> None:
    """Configure default logging when no application handlers are present."""
    if not logging.getLogger().handlers:
        logging.basicConfig(
            level=logging.INFO,
            format="%(asctime)s | %(levelname)s | %(name)s | %(message)s",
        )


def _call_ollama(model: str, system_prompt: str, user_prompt: str) -> str:
    """Call Ollama and return the response text."""
    try:
        import ollama  # type: ignore
    except ImportError as exc:
        raise ImportError("ollama package is required for patch explanation generation") from exc

    try:
        payload = ollama.chat(
            model=model,
            messages=[
                {"role": "system", "content": system_prompt},
                {"role": "user", "content": user_prompt},
            ],
        )
    except Exception as exc:
        raise RuntimeError(f"Ollama chat failed for model '{model}'") from exc

    if not isinstance(payload, dict):
        return str(payload).strip()

    message = payload.get("message", {})
    if isinstance(message, dict):
        content = message.get("content", "")
        if isinstance(content, str) and content.strip():
            return content.strip()
    return ""


def explain_rankings(ranked_cves: list[dict], top_k: int = 5) -> list[dict]:
    """Attach a brief Mistral explanation to the top-ranked CVEs.

    Args:
        ranked_cves: Output from :func:`modules.priority_scorer.rank_cves`.
        top_k: Number of top ranked CVEs to explain.

    Returns:
        A list of the original ranking dictionaries with an ``explanation`` field.
    """
    _configure_logging()
    explained: List[Dict[str, Any]] = []
    system_prompt = (
        "You are SecureRAG, a SOC analyst copilot. "
        "Answer concisely and factually using only the data provided."
    )

    for item in ranked_cves[: max(top_k, 0)]:
        cve_id = str(item.get("cve_id", "")).strip().upper()
        cvss_score = float(item.get("cvss_score", 0.0) or 0.0)
        epss_score = float(item.get("epss_score", 0.0) or 0.0)
        kev_flag = int(item.get("kev_flag", 0) or 0)
        rank = int(item.get("rank", 0) or 0)

        user_prompt = (
            f"CVE: {cve_id} | CVSS: {cvss_score} | EPSS: {epss_score * 100:.1f}% | "
            f"KEV: {'CONFIRMED EXPLOITED' if kev_flag else 'Not in KEV'} | Rank: #{rank}\n\n"
            f"Explain in 3-4 sentences why this CVE is ranked #{rank}. Reference its CVSS severity, "
            f"EPSS 30-day exploitation probability, and CISA KEV status. End with a single recommended action for the SOC analyst."
        )

        LOGGER.info("Explaining ranking for %s", cve_id)
        explanation = _call_ollama(DEFAULT_MODEL, system_prompt, user_prompt)
        explained.append({**item, "explanation": explanation})

    return explained


def generate_priority_report(cve_list: list[str], weights: dict = WEIGHTS_MAIN) -> dict:
    """Generate a ranked CVE report with LLM explanations.

    Args:
        cve_list: CVE identifiers to score.
        weights: Weight preset used for scoring.

    Returns:
        A dictionary containing ranked CVEs, the timestamp, and the weights used.
    """
    _configure_logging()
    ranked = rank_cves(cve_list, weights)
    explained = explain_rankings(ranked, top_k=len(ranked))
    return {
        "ranked_cves": explained,
        "timestamp": datetime.now(timezone.utc).isoformat(),
        "weights_used": dict(weights),
    }


def main() -> int:
    """Manual smoke-test entrypoint."""
    sample = ["CVE-2021-44228", "CVE-2022-26134", "CVE-2023-44487"]
    report = generate_priority_report(sample)
    print(report)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())